### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [mario-campos/xget#47]
I have seen that [no loop is used around a call](https://github.com/mario-campos/xget/blob/9a72635a48953ab750c49d07f793dfbeada8413e/xget.c#L196 "Update candidate: thread_progress()") of the function “[pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "Wait on a condition")”.
Would you like to reuse anything from my message on the topic “[spurious wakeup](https://groups.google.com/d/msg/comp.programming.threads/Gpe38hgZlsQ/1_1SRoCZgrsJ)”?

**Comment by mario-campos** [comment]
Thanks for the suggestion. I've made the fix. Will upload it soon.

**Comment by elfring** [comment]
Thanks for [your small source code adjustment](https://github.com/mario-campos/xget/commit/f3aadc8d2a04e61437d10e7d5f7e0fae60dde05d "Protect against spurious wake-ups.").
